Update Field.d.ts to handle "label" attribute
SynchValidation and ASyncValidation examples from redux-form gives the error below since it cannot find label.

error TS2339: Property 'label' does not exist on type '(IntrinsicAttributes & IntrinsicClassAttributes<Field<GenericFieldHTMLAttributes>> & Readonly<{ c...'.